export var
    PROGRAM_NODE = 0,
    KEYWORD_NODE = 1,
    BLOCK_NODE = 2,

    STRING_CONTENT_NODE = 3,
    
    WHITESPACE_NODE = 4,
    VARIABLE_NODE = 5,
    SIGN_NODE = 6,

    ONELINE_COMMENT_NODE = 7,
    COMMENT_NODE = 8,

    NUMBER_NODE = 9,

    UNKNOWN_NODE = 10
;
