
export var
    BLOCK_STATEMENT_NODE = 0,
    EMPTY_STATEMENT_NODE = 1,
    VAR_DECLARATION_NODE = 2,

    FUNCTION_DECLARATION_NODE = 3,
    FUNCTION_EXPRESSION_NODE = 4,

    ARROW_FUNCTION_EXPRESSION_NODE = 5,
    TEMPLATE_STRING_TAG_EXPRESSION_NODE = 6,

    LABELED_STATEMENT_NODE = 7,
    IF_STATEMENT_NODE = 8,
    FOR_STATEMENT_NODE = 9,
    WHILE_STATEMENT_NODE = 10,
    RETURN_STATEMENT_NODE = 11,
    BREAK_STATEMENT_NODE = 12,
    DEBUGGER_STATEMENT_NODE = 13,
    IMPORT_DECLARATION_NODE = 14,
    EXPORT_NAMED_DECLARATION_NODE = 15,
    EXPORT_DEFAULT_DECLARATION_NODE = 16,
    EXPORT_ALL_DECLARATION_NODE = 17,
    IDENTIFIER_EXPRESSION_NODE = 18,
    THIS_EXPRESSION_NODE = 19,
    NUMBER_LITERAL_EXPRESSION_NODE = 20,
    ONE_QUOTE_STRING_LITERAL_EXPRESSION_NODE = 21,
    TWO_QUOTE_STRING_LITERAL_EXPRESSION_NODE = 22,
    TEMPLATE_STRING_LITERAL_EXPRESSION_NODE = 23,
    BOOLEAN_LITERAL_EXPRESSION_NODE = 24,
    NULL_LITERAL_EXPRESSION_NODE = 25,
    BIGINT_LITERAL_EXPRESSION_NODE = 26,
    REGULAR_EXPRESSION_LITERAL_EXPRESSION_NODE = 27,
    ARRAY_EXPRESSION_NODE = 28,
    OBJECT_EXPRESSION_NODE = 29,
    DOT_MEMBER_EXPRESSION_NODE = 30,
    COMPUTED_MEMBER_EXPRESSION_NODE = 31,
    
    CALL_EXPRESSION_NODE = 32,
    NEW_EXPRESSION_NODE = 33,
    
    EQUAL_ASSIGNMENT_EXPRESSION_NODE = 34,   // =
    PLUS_EQUAL_ASSIGNMENT_EXPRESSION_NODE = 35,          // +=
    MINUS_EQUAL_ASSIGNMENT_EXPRESSION_NODE = 36,         // -=
    MULTIPLY_EQUAL_ASSIGNMENT_EXPRESSION_NODE = 37,      // *=
    DIVIDE_EQUAL_ASSIGNMENT_EXPRESSION_NODE = 38,        // /=
    REMAINDER_EQUAL_ASSIGNMENT_EXPRESSION_NODE = 39,     // %=
    BITWISE_LEFT_SHIFT_EQUAL_ASSIGNMENT_EXPRESSION_NODE = 40,   // <<=
    BITWISE_RIGHT_SHIFT_EQUAL_ASSIGNMENT_EXPRESSION_NODE = 41,  // >>=
    BITWISE_UNSIGNED_RIGHT_SHIFT_EQUAL_ASSIGNMENT_EXPRESSION_NODE = 42, // >>>=
    BITWISE_OR_EQUAL_ASSIGNMENT_EXPRESSION_NODE = 43,    // |=
    BITWISE_AND_EQUAL_ASSIGNMENT_EXPRESSION_NODE = 44,   // &=
    BITWISE_XOR_EQUAL_ASSIGNMENT_EXPRESSION_NODE = 45,   // ^=
    POWER_EQUAL_ASSIGNMENT_EXPRESSION_NODE = 46,         // **=
    LOGICAL_AND_EQUAL_ASSIGNMENT_EXPRESSION_NODE = 47,   // &&=
    LOGICAL_OR_EQUAL_ASSIGNMENT_EXPRESSION_NODE = 48,    // ||=
    NULLISH_COALESCING_EQUAL_ASSIGNMENT_EXPRESSION_NODE = 49, // ??=

    PLUS_EXPRESSION_NODE = 50,          // +
    MINUS_EXPRESSION_NODE = 51,         // -
    MULTIPLY_EXPRESSION_NODE = 52,      // *
    DIVIDE_EXPRESSION_NODE = 53,        // /
    REMAINDER_EXPRESSION_NODE = 54,     // %
    BITWISE_LEFT_SHIFT_EXPRESSION_NODE = 55,   // <<
    BITWISE_RIGHT_SHIFT_EXPRESSION_NODE = 56,  // >>
    BITWISE_UNSIGNED_RIGHT_SHIFT_EXPRESSION_NODE = 57, // >>>
    BITWISE_OR_EXPRESSION_NODE = 58,    // |
    BITWISE_AND_EXPRESSION_NODE = 59,   // &
    BITWISE_XOR_EXPRESSION_NODE = 60,   // ^
    POWER_EXPRESSION_NODE = 61,         // **
    LOGICAL_AND_EXPRESSION_NODE = 62,   // &&
    LOGICAL_OR_EXPRESSION_NODE = 63,    // ||
    NULLISH_COALESCING_EXPRESSION_NODE = 64, // ??
    NONSTRICT_EQUAL_EXPRESSION_NODE = 65, // ==
    STRICT_EQUAL_EXPRESSION_NODE = 66, // ===
    NONSTRICT_NONEQUAL_EXPRESSION_NODE = 67, // !=
    STRICT_NONEQUAL_EXPRESSION_NODE = 68, // !==

    VOID_EXPRESSION_NODE = 69, // void

    UNARY_PLUS_EXPRESSION_NODE = 70, // +a
    UNARY_MINUS_EXPRESSION_NODE = 71, // -b
    LOGICAL_NOT_EXPRESSION_NODE = 72, // !
    BITWISE_NOT_EXPRESSION_NODE = 73, // ~

    INCREMENT_EXPRESSION_NODE = 74, // ++
    DECREMENT_EXPRESSION_NODE = 75, // --

    TERNARY_QUESTION_MARK_EXPRESSION_NODE = 76, // ?
    TERNARY_COLON_EXPRESSION_NODE = 77, // :

    SEQUENCE_EXPRESSION_NODE = 78,           // ,
    
    PROPERTY_NODE = 79,                      // { key: value }
    
    IMPORT_SPECIFIER_NODE = 80,              // import { a as b }
    IMPORT_DEFAULT_SPECIFIER_NODE = 81,      // import a from 'x'
    IMPORT_NAMESPACE_SPECIFIER_NODE = 82,    // import * as ns from 'x'
    EXPORT_SPECIFIER_NODE = 83,              // export { a as b }

    TEMPLATE_ELEMENT_NODE = 84,              // части template literal между вставками
    TEMPLATE_PASTE_ELEMENT_NODE = 85,        // вставка в template literal
    
    PARENTHESIZED_EXPRESSION_NODE = 86,

    WHITESPACE_NODE = 87,
    CONDITIONAL_EXPRESSION_NODE = 88
;
