
export default {
    10: [
        "constructor",
        "implements",
        "instanceof",
    ],
    9: [
        "interface",
        "protected",
    ],
    8: [
        "continue",
        "debugger",
        "function",
    ],
    7: [
        "default",
        "extends",
        "finally",
        "package",
        "private",
    ],
    6: [
        "delete",
        "export",
        "import",
        "public",
        "return",
        "static",
        "static",
        "switch",
        "typeof",
    ],
    5: [
        "async",
        "await",
        "break",
        "catch",
        "class",
        "class",
        "const",
        "false",
        "super",
        "throw",
        "using",
        "while",
        "yield",
    ],
    4: [
        "case",
        "else",
        "enum",
        "from",
        "null",
        "this",
        "true",
        "void",
        "with",
    ],
    3: [
        "for",
        "for",
        "get",
        "let",
        "new",
        "set",
        "try",
        "var",
    ],
    2: [
        "as",
        "do",
        "if",
        "in",
        "in",
        "of"
    ],
};